### ISSUE TITLE
BUG: hidden coversation profile when android keyboard shows 

### ISSUE THREAD

**Issue by mohsenD98** [mohsenD98/QmlZeroDay#7]

**Comment by MidnightCoder-m** [comment]
# the problem is When keyboard shows up the profile picture goes away ..! 

![photo_2022-08-05_20-00-59](https://user-images.githubusercontent.com/36326627/183110971-63cc4e59-d7b1-4f01-8ef6-346ec05b5130.jpg)

![photo_2022-08-05_20-01-03](https://user-images.githubusercontent.com/36326627/183110979-148ee09a-6146-47d1-96cf-93dd8d557346.jpg)

**Comment by MidnightCoder-m** [comment]
its been fixed by adding this in AndroidManifest.xml
`android:windowSoftInputMode="adjustResize"`
